# Khai báo thông tin dự án (nếu cần)
sonar.exclusions=**/*.json

# Loại trừ thư mục test khỏi việc tính toán trùng lặp code (Duplication)
sonar.cpd.exclusions=test/**, **/*.json, **/*.js

# Đánh dấu thư mục chứa test case
sonar.tests=test